puts "I will now count my chickens:"
puts "No of hens= #{25 + 30 / 6}"
puts "No of roosters= #{100 - 25 * 3 % 4}"
puts "#{3 + 2 + 1-5 + 4 % 2 - 1 / 4 + 6}"
puts "Now checking true or false"
puts "Is it true that 3+2 < 5-7?"
puts 3 + 2 < 5 - 7
puts "what is 3+2? #{3 + 2}"
puts "what is 5-2? #{5 - 7}"
puts "Oh that's why it is false."
puts "how about some more."
puts "Is it greater? #{3 + 2 > 5 - 7}"
puts "Is it greater or equal? #{3 + 2 >= 5 - 7}"
puts "Is it lesser or equal? #{3 + 2 <= 5 - 7} "
